/*function presidente( nombre, deudaNeta,deudaTotal,superficie_horizontalNeta_1usd, superficie_horizontalTotal_1usd,superficie_verticalNeta_1usd,superficie_verticalTotal_1usd, superficie_verticalTotal_1usd,superficie_horizontalNeta_Pesos,superficie_horizontalTotal_Pesos,superficie_verticalNeta_Pesos,superficie_verticalTotal_pesos)
{ this.nombre= nombre, this.deudaNeta=deudaNeta, this.deudaTotal= deudaTotal,this.superficie_horizontalNeta_1usd=superficie_horizontalNeta_1usd,this.superficie_horizontalTotal_1usd=superficie_horizontalTotal_1usd,this.superficie_verticalNeta_1usd=superficie_verticalNeta_1usd,this.superficie_verticalTotal_1usd=superficie_verticalTotal_1usd,this.superficie_verticalNeta_Pesos=superficie_verticalNeta_Pesos,this.superficie_verticalTotal_pesos=superficie_verticalTotal_pesos}

let Macri= new presidente( "Mauricio Macri",82400000000,323065000000,superficie_horizontalNeta_1usd,superficie_horizontalTotal_1usd,superficie_verticalNeta_1usd,superficie_verticalTotal_1usd,superficie_horizontalNeta_Pesos,superficie_horizontalTotal_Pesos,superficie_verticalNeta_Pesos,superficie_verticalTotal_pesos);
let Cristina= new presidente("Cristina Fernandez de kirchner",75554000000,240665000000,superficie_horizontalNeta_1usd,superficie_horizontalTotal_1usd,superficie_verticalNeta_1usd,superficie_verticalTotal_1usd,superficie_horizontalNeta_Pesos,superficie_horizontalTotal_Pesos,superficie_verticalNeta_Pesos,superficie_verticalTotal_pesos)

ArrayPresidentes=[ Macri,Cristina ];

https://www.argentina.gob.ar/coronavirus/vacuna/aplicadas

https://www.batimes.com.ar/news/argentina/shipment-of-900000-sinopharm-vaccine-doses-arrives-in-argentina.phtml
*/
[{ "aplicadas":5935146,"valorpeso":110}]